+==============================================================================+

                               /$$$$$$            /$$
                              /$$__  $$          | $$
           /$$$$$$$  /$$$$$$ | $$  \__//$$$$$$  /$$$$$$   /$$   /$$
          /$$_____/ |____  $$| $$$$   /$$__  $$|_  $$_/  | $$  | $$
         |  $$$$$$   /$$$$$$$| $$_/  | $$$$$$$$  | $$    | $$  | $$
          \____  $$ /$$__  $$| $$    | $$_____/  | $$ /$$| $$  | $$
          /$$$$$$$/|  $$$$$$$| $$    |  $$$$$$$  |  $$$$/|  $$$$$$$
         |_______/  \_______/|__/     \_______/   \___/   \____  $$
                                                          /$$  | $$
                                                         |  $$$$$$/
  by pyup.io                                              \______/

+==============================================================================+

 REPORT 

  Safety is using PyUp's free open-source vulnerability database. This
data is 30 days old and limited. 
  For real-time enhanced vulnerability data, fix recommendations, severity
reporting, cybersecurity support, team and project policy management and more
sign up at https://pyup.io or email sales@pyup.io

  Safety v2.3.5 is scanning for Vulnerabilities...
  Scanning dependencies in your environment:

  -> c:\users\bradl\desktop\lenz-api\env\lib\site-packages

  Using non-commercial database
  Found and scanned 82 packages
  Timestamp 2023-11-19 20:56:23
  2 vulnerabilities found
  0 vulnerabilities ignored

+==============================================================================+
 VULNERABILITIES FOUND 
+==============================================================================+

-> Vulnerability found in setuptools version 65.5.0
   Vulnerability ID: 52495
   Affected spec: <65.5.1
   ADVISORY: Setuptools 65.5.1 includes a fix for CVE-2022-40897: Python
   Packaging Authority (PyPA) setuptools before 65.5.1 allows remote attackers
   to cause a denial of service via HTML in a crafted package or custom
   PackageIndex page. There is a Regular Expression Denial of Service (ReDoS) in
   package_index.py.https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-
   in-top-python-packages
   CVE-2022-40897
   For more information, please visit
   https://data.safetycli.com/v/52495/f17


-> Vulnerability found in django version 4.2.5
   Vulnerability ID: 61586
   Affected spec: >=4.2a1,<4.2.6
   ADVISORY: Django 4.2.6, 4.1.12 and 3.2.22 include a fix for
   CVE-2023-43665: Denial-of-service possibility in django.utils.text.Truncator.
   The django.utils.text.Truncator chars() and words() methods (when used with
   html=True) are subject to a potential DoS (denial of service) attack via
   certain inputs with very long, potentially malformed HTML text. The chars()
   and words() methods are used to implement the truncatechars_html and
   truncatewords_html template filters, which are thus also vulnerable. NOTE:
   this issue exists because of an incomplete fix for
   CVE-2019-14232.https://www.djangoproject.com/weblog/2023/oct/04/security-
   releases
   CVE-2023-43665
   For more information, please visit
   https://data.safetycli.com/v/61586/f17

 Scan was completed. 2 vulnerabilities were found. 

+==============================================================================+
   REMEDIATIONS

  2 vulnerabilities were found in 2 packages. For detailed remediation & fix 
  recommendations, upgrade to a commercial license. 

+==============================================================================+

  Safety is using PyUp's free open-source vulnerability database. This
data is 30 days old and limited. 
  For real-time enhanced vulnerability data, fix recommendations, severity
reporting, cybersecurity support, team and project policy management and more
sign up at https://pyup.io or email sales@pyup.io

+==============================================================================+
